Repository MHeironimus/ArduinoJoystickLibrary, pull requests merged in 2020-06, with the labels that each got.

#150 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/support-new-board.md
  issue_template.md
  pull_request_template.md
Labels: documentation

#151 Community Updates 1
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/support-new-board.md
  README.md
  deploy.bat
  deploy.sh
  examples/DrivingControllerTest/DrivingControllerTest.ino
  examples/FlightControllerTest/FlightControllerTest.ino
  examples/GamepadExample/GamepadExample.ino
  examples/HatSwitchTest/HatSwitchTest.ino
  examples/JoystickButton/JoystickButton.ino
  examples/JoystickKeyboard/JoystickKeyboard.ino
  examples/JoystickTest/JoystickTest.ino
  examples/MultipleJoystickTest/MultipleJoystickTest.ino
  issue_template.md
  library.properties
  pull_request_template.md
  src/DynamicHID/DynamicHID.cpp
  src/DynamicHID/DynamicHID.h
  src/Joystick.cpp
  src/Joystick.h
Labels: documentation, enhancement

#152 Version 2.0.6 - Community Updates 1
  README.md
  deploy.bat
  deploy.sh
  examples/DrivingControllerTest/DrivingControllerTest.ino
  examples/FlightControllerTest/FlightControllerTest.ino
  examples/GamepadExample/GamepadExample.ino
  examples/HatSwitchTest/HatSwitchTest.ino
  examples/JoystickButton/JoystickButton.ino
  examples/JoystickKeyboard/JoystickKeyboard.ino
  examples/JoystickTest/JoystickTest.ino
  examples/MultipleJoystickTest/MultipleJoystickTest.ino
  library.properties
  src/DynamicHID/DynamicHID.cpp
  src/DynamicHID/DynamicHID.h
  src/Joystick.cpp
  src/Joystick.h
Labels: documentation, enhancement

#121 Change DynamicHID.h include from <> to "" to allow use outside Arudino libraries directory
  Joystick/src/Joystick.h
Labels: enhancement

#89 Move library to root of repository
  README.md
  deploy.bat
  deploy.sh
  examples/DrivingControllerTest/DrivingControllerTest.ino
  examples/FlightControllerTest/FlightControllerTest.ino
  examples/GamepadExample/GamepadExample.ino
  examples/HatSwitchTest/HatSwitchTest.ino
  examples/JoystickButton/JoystickButton.ino
  examples/JoystickKeyboard/JoystickKeyboard.ino
  examples/JoystickTest/JoystickTest.ino
  examples/MultipleJoystickTest/MultipleJoystickTest.ino
  library.properties
  src/DynamicHID/DynamicHID.cpp
  src/DynamicHID/DynamicHID.h
  src/Joystick.cpp
  src/Joystick.h
Labels: enhancement
